### ISSUE TITLE
Flutter web cannot get starting provider 

### ISSUE THREAD

**Issue by Kassan424kh** [rrousselGit/provider#249]
<img src="https://i.ibb.co/JcG8TRR/Screenshot-2019-10-17-at-16-15-31.png">

```DART
import 'package:berichtsheft_app/Components/home_page.dart';
import 'package:berichtsheft_app/provider/navigation_provider.dart';
import 'package:berichtsheft_app/provider/styling_provider.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  return runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(builder: (context) => NavigationProvider()),
        ChangeNotifierProvider(builder: (context) => StylingProvider()),
      ],
      child: MyApp(),
    )
    );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Berichtsheft",
      home: Web(),
    );
  }
}

```

```LOG
▶ flutter run -d chrome
 
Launching lib/main.dart on Chrome in debug mode...
Throwing away cached asset graph because the build phases have changed. This most
commonly would happen as a result of adding a new dependency or updating your
dependencies.
Error compiling dartdevc module:berichtsheft_app|lib/Components/home_page.ddc.js

packages/berichtsheft_app/Components/home_page.dart:21:54: Error: The argument type
'BuildContext/*1*/' can't be assigned to the parameter type 'BuildContext/*2*/'.
 - 'BuildContext/*1*/' is from 'package:flutter/src/widgets/framework.dart'
 ('packages/flutter/src/widgets/framework.dart').
 - 'BuildContext/*2*/' is from 'package:flutter_web/src/widgets/framework.dart'
 ('packages/flutter_web/src/widgets/framework.dart').
    final navigate = Provider.of<NavigationProvider>(context);
                                                     ^
packages/berichtsheft_app/Components/home_page.dart:47:59: Error: The argument type
'BuildContext/*1*/' can't be assigned to the parameter type 'BuildContext/*2*/'.
 - 'BuildContext/*1*/' is from 'package:flutter/src/widgets/framework.dart'
 ('packages/flutter/src/widgets/framework.dart').
 - 'BuildContext/*2*/' is from 'package:flutter_web/src/widgets/framework.dart'
 ('packages/flutter_web/src/widgets/framework.dart').
              child: Text(Provider.of<NavigationProvider>(context).selectedPage),
                                                          ^
packages/berichtsheft_app/Components/home_page.dart:122:54: Error: The argument
type 'BuildContext/*1*/' can't be assigned to the parameter type
'BuildContext/*2*/'.
 - 'BuildContext/*1*/' is from 'package:flutter/src/widgets/framework.dart'
 ('packages/flutter/src/widgets/framework.dart').
 - 'BuildContext/*2*/' is from 'package:flutter_web/src/widgets/framework.dart'
 ('packages/flutter_web/src/widgets/framework.dart').
    final navigate = Provider.of<NavigationProvider>(context);
                                                     ^


Error compiling dartdevc module:berichtsheft_app|lib/main.ddc.js        

packages/berichtsheft_app/main.dart:11:9: Error: Inferred type argument
'NavigationProvider' doesn't conform to the bound 'ChangeNotifier' of the type
variable 'T' on 'ChangeNotifierProvider'.
 - 'NavigationProvider' is from
 'package:berichtsheft_app/provider/navigation_provider.dart'
 ('packages/berichtsheft_app/provider/navigation_provider.dart').
 - 'ChangeNotifier' is from
 'package:flutter_web/src/foundation/change_notifier.dart'
 ('packages/flutter_web/src/foundation/change_notifier.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
        ChangeNotifierProvider(builder: (context) => NavigationProvider()),
        ^
packages/berichtsheft_app/main.dart:12:9: Error: Inferred type argument
'StylingProvider' doesn't conform to the bound 'ChangeNotifier' of the type
variable 'T' on 'ChangeNotifierProvider'.
 - 'StylingProvider' is from
 'package:berichtsheft_app/provider/styling_provider.dart'
 ('packages/berichtsheft_app/provider/styling_provider.dart').
 - 'ChangeNotifier' is from
 'package:flutter_web/src/foundation/change_notifier.dart'
 ('packages/flutter_web/src/foundation/change_notifier.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
        ChangeNotifierProvider(builder: (context) => StylingProvider()),
        ^
packages/berichtsheft_app/main.dart:14:14: Error: The argument type 'MyApp' can't
be assigned to the parameter type 'Widget'.
 - 'MyApp' is from 'package:berichtsheft_app/main.dart'
 ('packages/berichtsheft_app/main.dart').
 - 'Widget' is from 'package:flutter_web/src/widgets/framework.dart'
 ('packages/flutter_web/src/widgets/framework.dart').
      child: MyApp(),
             ^
packages/berichtsheft_app/main.dart:9:5: Error: The argument type 'MultiProvider'
can't be assigned to the parameter type 'Widget'.
 - 'MultiProvider' is from 'package:provider/src/provider.dart'
 ('packages/provider/src/provider.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart'
 ('packages/flutter/src/widgets/framework.dart').
    MultiProvider(
    ^


                                                                        
AssetNotFoundException: berichtsheft_app|lib/Components/home_page.ddc.js
Failed after 28.0s                                                      
Building application for the web...                                40.7s
Failed to build application for the Web.
```

```YAML
name: berichtsheft_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_web: any
  flutter_web_ui: any
  provider: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
