### ISSUE TITLE
Update ProviderNotFoundError to include recommendation about nullable providers

### ISSUE THREAD

**Issue by miriam-z** [rrousselGit/provider#620]
After splashscreen loads and next screen appears :

Error: Could not find the correct Provider<User> above this AuthenticationWrapper Widget.

main.dart

```
import 'dart:convert';
import 'package:facebook_auth_example/authentication_service.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_signin_button/flutter_signin_button.dart';
import 'package:animated_splash_screen/animated_splash_screen.dart';
import 'package:page_transition/page_transition.dart';
import 'package:google_sign_in/google_sign_in.dart';

import 'dart:convert' show json;
import 'package:http/http.dart' as http;
import 'package:provider/provider.dart';
import 'package:svg_path_parser/svg_path_parser.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthenticationService>(
          create: (_) => AuthenticationService(FirebaseAuth.instance),
        ),
        StreamProvider(
          create: (context) =>
              context.read<AuthenticationService>().authStateChanges,
          initialData: 0
        ),
      ],
      child: MaterialApp(
          title: 'New Clean Code',
          // home: AuthenticationWrapper()),
          home: AnimatedSplashScreen(
              duration: 3000,
              splash: Icons
                  .home, //'assets/images/text_psymlify.png', //images/text_psymplify.png', // Icons.home
              nextScreen: AuthenticationWrapper(), // LoginScreen(),
              splashTransition: SplashTransition.slideTransition,
          pageTransitionType: PageTransitionType.bottomToTop,
          backgroundColor: Colors.yellow)),
    );
  }
}

class AuthenticationWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final firebaseUser = context.watch<User>();

    if (firebaseUser != null) {
      return Text("Signed In");
    }

    return Text("Not signed in");
  }
}
```

authentication_service.dart

```
import 'package:firebase_auth/firebase_auth.dart';

class AuthenticationService {
  final FirebaseAuth _firebaseAuth;

  AuthenticationService(this._firebaseAuth);

  Stream<User> get authStateChanges => _firebaseAuth.authStateChanges();

  Future<String> signIn({String email, String password}) async {
    try {
      await _firebaseAuth.signInWithEmailAndPassword(
          email: email, password: password);
      return "Signed In";
    } on FirebaseAuthException catch (e) {
      return e.message;
    }
  }

  Future<String> signUp({String email, String password}) async {
    try {
      await _firebaseAuth.createUserWithEmailAndPassword(
          email: email, password: password);
      return "Signed up";
    } on FirebaseAuthException catch (e) {
      return e.message;
    }
  }
}

```

pubspec.yaml

 
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  change_app_package_name: ^0.1.2
  flutter_facebook_auth: ^3.0.0+1

  firebase_auth: ^1.0.1
  firebase_auth_platform_interface: ^4.0.0
  firebase_auth_web: ^1.0.2
  firebase_core: ^1.0.1

  meta: ^1.3.0

  cloud_firestore: ^1.0.1
  flutter_signin_button: ^2.0.0-nullsafety.0
  google_sign_in: ^5.0.0
  google_sign_in_platform_interface: ^2.0.1
  google_sign_in_web: ^0.10.0
  
  http: ^0.13.0
  provider: ^5.0.0

  font_awesome_flutter: ^9.0.0-nullsafety
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.1-nullsafety.0
  svg_path_parser: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      # - images/start.svg
      # - images/text_psymplify.svg
      - assets/images/
```
 

![Screenshot 2021-03-12 at 17 28 27](https://user-images.githubusercontent.com/19760229/110976074-5e74b680-8358-11eb-8b26-d992fa8cf916.png)
