### ISSUE TITLE
Flutter Web  support

### ISSUE THREAD

**Issue by dbacinski** [rrousselGit/provider#82]
Can we get repackeged version of provider library for Flutter Web?

Flutter Web is using widgets from package:flutter_web instead of package:flutter.

**Comment by rrousselGit** [comment]
That's something you can/should do yourself by forking `provider`.


A few others did already (like kevmo) . You may as well use theirs.

**Comment by dbacinski** [comment]
```
dependencies:
  flutter_web: any
  flutter_web_ui: any
  provider: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web
```

solved it like above, provider lib is being overridden by kevmoo fork on branch flutter_web
