### ISSUE TITLE
DevTools failed to connect with package:provider

### ISSUE THREAD

**Issue by MinByeongDon** [rrousselGit/provider#859]
**Describe the bug**

The following error message is displayed:

![image](https://github.com/rrousselGit/provider/assets/6141807/0846bfcc-096c-491a-819e-6e8d4121973e)
![image](https://github.com/rrousselGit/provider/assets/6141807/d94bcf18-6c08-404f-8d17-e2056877588c)

But in "pubspec.yaml" it is defined as "provider: ^6.1.1":

```yaml
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_hooks: ^0.20.3
  intl: ^0.18.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  custom_lint: ^0.5.11
```

flutter doctor:

```text
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] VS Code (version 1.86.0-insider)
[✓] Connected device (2 available)
[✓] Network resources
```

**Expected behavior**

It looks like the Provider inspector of DevTools should be connected correctly.
Thanks.

**Comment by MinByeongDon** [comment]
I misunderstood that providers from pkg:Riverpod are also displayed.
I have verified that using providers from pkg:Provider works fine and shows up.
![image](https://github.com/rrousselGit/provider/assets/6141807/a11d82c2-bdac-48d9-9730-7cf34918210e)

Please close the issue if you are correct that pkg:Riverpod's providers are not displayed.
Sorry for the hassle. Thanks

**Comment by rrousselGit** [comment]
Indeed, providers from pkg:Riverpod aren't supported. A separate devtool is planned

**Comment by Bus42** [comment]
I see this has been marked as completed, but I am experiencing the same issue and I'm not using Riverpod. Here and my env and dependencies in pubspec.yaml:
```
...
version: 1.0.0+1

environment:
  sdk: ">=3.2.0-42.2.beta <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_appauth: ^6.0.1
  flutter_dotenv: ^5.0.2
  http: ^1.0.0
  provider: ^6.0.5
  auth0_flutter: ^1.2.1
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.2
  # SDK Package used to interact with the Story Squad API
  story_squad_sdk:
    path: ../story_squad_sdk
    # git:
    #   url: git@github.com:<hidden>.git
    #   ref: dev-staging
  # Game Plugins
  storyflix:
    path: ../storyflix
    # git:
    #   url: git@github.com:<hidden>.git
    #   ref: dev-staging
  clash_of_the_pencils:
    path: ../clash_of_the_pencils_fe
    # git:
    #   url: git@github.com:<hidden>.git
    #   ref: dev-staging

  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  uuid: ^4.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
...
```
